### ISSUE TITLE
Detail Member kadang tak berjalan semestinya

### ISSUE THREAD

**Issue by Andirohandi** [phpindonesia/phpindonesia.or.id-membership2#10]
ini errro nya om The template "membership/detail" producing error. Undefined index: , on file: /home/phpindonesia/www/dev-spirit-front/protected/views/membership/detail.php, on line: 38

url saat load : http://www.phpindonesia.or.id/apps/membership/detail/zakyymuh

**Comment by zakyymuh** [comment]
jadi sewaktu registrasi kan disana ada form sosial media, nah saya isi dengan zakyymuh.xyz
jadi dampak ke akun sama detail mas

The template "sections::flash-message-success" producing error. Undefined index: , on file: /home/phpindonesia/www/dev-spirit-front/protected/views/membership/profile.php, on line: 44

**Comment by okaprinarjaya** [comment]
Halooo @Andirohandi ,

Iya betul, itu karena isian sosmed diisi dengan data ngawur. Dan memang terlewatkan untuk memvalidasi saat pilihan jenis sosmed tidak dipilih. Item sosmed mas Andi sudah saya delete. Jadi, silahkan untuk mengisi data yg valid.
