### ISSUE TITLE
Hapus folder vendor, commit composer.json dan composer.lock

### ISSUE THREAD

**Issue by virtualpain** [phpindonesia/phpindonesia.or.id-membership2#11]
Dengan begini harapannya sih codebase jadi lebih sedikit, dependensi mudah ditambah, diupdate, atau diganti. 

Mas @feryardiant sudah menunjukkan #4 dan sepertinya sudah nggak bisa diganggu gugat. Buat bang @okaprinarjaya, tolong kasih tahu alasannya dong kenapa kita masih harus meng-ignore `composer.json` dan `composer.lock`?

**Comment by nevrending** [comment]
+1 untuk hapus folder vendor dan commit `composer.json`

Ikut menyimak juga untuk alasan nya mengapa #4 di reject

**Comment by dnaextrim** [comment]
jadi susah untuk update, bahkan menambah library lain menggunakan composer require jadi menghapus library yang sudah terinstall, file composer.json mungkin jangan di ignore

**Comment by okaprinarjaya** [comment]
Kami menyebutnya tahap / phase pengembangan fungsionalitas. Jadi, kami HANYA fokus dan PEDULI terhadap pengembangan fungsionalitas. Kami amat sangat paham dengan maksud teman-teman yang tidak setuju mengapa kami sengaja include folder vendor di repository. 

Saya menyadari akan ada lagi lagi dan lagi orang yg protes terhadap strategi ini. Dan anehnya mengapa tidak ada yg peduli dengan pengembangan fungsionalitas? Mayoritas hanya peduli dengan hal - hal yg tidak terkait dengan pengembangan fungsionalitas.

**Comment by feryardiant** [comment]
Well, sedikit refrensi aja bang @okaprinarjaya. Repo ini pake Slim 3.x yang status nya masih heavy development dan kalo kita [dibandingkan perubahan](https://github.com/slimphp/Slim/compare/ea0827e...e7f3c08) yang ada dari repo ini ke upstream udah keliatan ada 77 commit dan pastinya banyak juga perubahan dalam hal _fungsionalitas_ disitu.
