### ISSUE TITLE
Pendaftaran

### ISSUE THREAD

**Issue by hawkeye33** [phpindonesia/phpindonesia.or.id-membership2#13]
ketika ada kesalahan isian, form "pilih kota" tdk ada pilihan
harus pilih provinsi lain dahulu baru bisa muncul
![screenshot_3](https://cloud.githubusercontent.com/assets/4981683/10914416/e0be133c-8284-11e5-9a98-ad16cc3b6e72.jpg)

**Comment by okaprinarjaya** [comment]
Ini sudah kami catat di system project management kami di https://taiga.io/ 
Bagi yg berminat mengerjakan ini, silahkan kontak saya by PM.

**Comment by titounnes** [comment]
saran. event untuk mengambil data kota jangan hanya berdasarkan onchange di propinsi taspi tambsahkan juga onfocus pada kpota manakala data propinsi tidak null.
