### ISSUE TITLE
Butuh sanitasi input. 

### ISSUE THREAD

**Issue by jafarpagerjaya** [phpindonesia/phpindonesia.or.id-membership2#16]
Nama lengkap masih bisa diisi capital di tengah atau di akhir mas, 
![image](https://cloud.githubusercontent.com/assets/15641645/10924958/09be1d9e-82bd-11e5-8b8d-3e608d5a3d8f.png)
Ini adalah format yang ane isikan ketika di pendaftaran dan saat di cek di update profile rupanya nama lengkap belum difilter sehingga isi di database sama seperti ini.
![image](https://cloud.githubusercontent.com/assets/15641645/10925133/33b84326-82be-11e5-8993-c19930b17ee7.png)
Nama lengkap dibagian update profile bisa disisipi script jg, sampe akhirnya ngebug data akun error

**Comment by feryardiant** [comment]
Saya rasa ini justru fitur lho bang. Fitur untuk member2 yang masih 4LaY :sweat_smile: 

Kayaknya facebook pun gak ada filter macam ini kan?

**Comment by okaprinarjaya** [comment]
Haaayyy mas @jafarpagerjaya , 

Terimakasih untuk laporannya, kami melewatkan bagian sanitasi input. Kami akan segera menambahkan sanitasi input. Untuk isian nama lengkap bisa ber-alay2 seperti itu kami skip dulu..

**Comment by okaprinarjaya** [comment]
Done.
Belum di-merge ke branch master. Akan tetapi sudah diupload ke production server. Sekarang di production sudah cover handling input sanitize
