### ISSUE TITLE
Pilihan kabupaten / kota seharusnya tetap terpilih saat ada isian lain yg belum benar

### ISSUE THREAD

**Issue by okaprinarjaya** [phpindonesia/phpindonesia.or.id-membership2#19]

**Comment by feryardiant** [comment]
I'm on it

**Comment by feryardiant** [comment]
Damn

**Comment by okaprinarjaya** [comment]
klo issue2 / task gak digeser ke kolom yg sesuai, 
ngapain juga kita pakai tools macem zenhub gini ya?
mending uninstall aja kali yaa ni tools project management?

**Comment by feryardiant** [comment]
Lho kan sebagai kontributor saya nunggu review owner dulu..

Best, Fery.

On Nov 5, 2015 22:28, Oka Prinarjaya notifications@github.com wrote:

klo issue2 / task gak digeser ke kolom yg sesuai, 
ngapain juga kita pakai tools macem zenhub gini ya?
mending uninstall aja kali yaa ni tools project management?

**Comment by feryardiant** [comment]
Btw, saya kok liat ada tombol atau drag handler untuk mindah ke kolom lain ya?

**Comment by okaprinarjaya** [comment]
Tidak apa2 mas Fery, langsung geser aja ke kolom yg sesuai. 
Saya perlu langsung melihat situasi. Siapa siapa mengerjakan apa.
Nnti review langsung di level pull request aja.

**Comment by okaprinarjaya** [comment]
Oh iya? kok bisa gak ada ya? gak ada kan maksudnya?
apa jangan2... cuma owner yg bisa manage.

**Comment by okaprinarjaya** [comment]
coba check lagi.. barusan saya setting permission.

**Comment by feryardiant** [comment]
Bisa geser, tapi

![php indonesia - membership](https://cloud.githubusercontent.com/assets/508665/10973785/84d643da-8411-11e5-80bf-d364958a913a.png)
