### ISSUE TITLE
Member yg belum activated,  dapat aktivasi ulang karena keterlambatan penerimaan email

### ISSUE THREAD

**Issue by okaprinarjaya** [phpindonesia/phpindonesia.or.id-membership2#22]
Member yg belum activated,  dapat aktivasi ulang karena keterlambatan penerimaan email

**Comment by feryardiant** [comment]
Kayaknya ini udah pernah solved deh?

Sementara saya close dulu ya sambil ngerjain yang PR #96 nanti saya check lagi.
