### ISSUE TITLE
Butuh menyimpan asset gambar di CDN Cloudinary

### ISSUE THREAD

**Issue by okaprinarjaya** [phpindonesia/phpindonesia.or.id-membership2#24]
in progress by @feryardiant

**Comment by feryardiant** [comment]
Gak perlu cepet-cepet kan bang? masih ada kerjaan lain soalnya :grin:

**Comment by okaprinarjaya** [comment]
Santai saja, yg penting selesai dan berfungsi :)
Mas Fery sudah gabung di zenhub.io ?

**Comment by feryardiant** [comment]
Oya oot dikit ya.

Untuk refrensi ku yang kemaren soal zenhub dan sweepboard udah direview?

---

Best :)
Fery Wardiyanto

2015-11-04 23:10 GMT+07:00 Oka Prinarjaya notifications@github.com:

**Comment by okaprinarjaya** [comment]
Lhaa?? undangannya belum masuk ya?
malah saya sudah pindahkan semua task ke zenhub.io 
Saya sudah invite via zenhub.

**Comment by feryardiant** [comment]
Belum kayaknya oya zenhub itu otomatis include semua orang yang ada dalam
github organization. tp qu belum tau kalo external contributor.

---

Best :)
Fery Wardiyanto

**Comment by okaprinarjaya** [comment]
Terimakasih banyak banyak mas @feryardiant atas bantuannya, ini sangat membantu.
