### ISSUE TITLE
Update session setelah update profile

### ISSUE THREAD

**Issue by chabibnr** [phpindonesia/phpindonesia.or.id-membership2#34]
sepertinya pada saat seletelah update profil session tidak ada perubahan,
seperti : gambar thumnail yang ada di menu belum berubah setelah profil disimpan

**Comment by feryardiant** [comment]
Ada screenshot?

**Comment by chabibnr** [comment]
![screenshot_11](https://cloud.githubusercontent.com/assets/4100006/10961630/587dd030-83c3-11e5-9b71-8499b310e05a.png)

**Comment by okaprinarjaya** [comment]
Solved
