### ISSUE TITLE
Kalimantan utara, provinsi baru pecahan dari kalimantan timur belum ada

### ISSUE THREAD

**Issue by okaprinarjaya** [phpindonesia/phpindonesia.or.id-membership2#37]
Ada Provinsi baru yaitu: kalimantan utara. Pecahan dr kalimantan timur. Kota kabupaten daerah belum ada

**Comment by ceceprawiro** [comment]
https://id.wikipedia.org/wiki/Kabupaten_Banggai

Luwuk adalah kecamatan (ibukota kab. Banggai). Gmn nih, om? Kita datanya belom sampe kecamatan.
Untuk yg Kalut, udah ada kota: Tarakan.
