### ISSUE TITLE
[BUG] update portfolio

### ISSUE THREAD

**Issue by SunDi3yansyah** [phpindonesia/phpindonesia.or.id-membership2#40]
## issue

Dibutuhkan validasi query parameter where untuk role si pembuat portfolio menghindari celah kemanan own portfolio tiap member

![screenshot from 2015-11-08 01 27 55](https://cloud.githubusercontent.com/assets/3952281/11016556/2bae637a-85b8-11e5-9a75-f2f6a1e0e256.png)

> Mohon maaf untuk 3 portfolio untuk saya uji coba, hanya data **Nama Perusahaan** yang saya rubah. ID 1, 2 dan 3 bidang lainnya sudah saya restore :neckbeard:

_[content deleted]_

email: [sundi3yansyah@gmail.com](mailto:sundi3yansyah@gmail.com)
## question

Saya pengguna NGINX bagaimana untuk membuat aturan server pada framework slim?
Pada saat ini config nginx saya pada host phpindonesia seperti berikut, upaya saya sudah membentuk config ke FW slim namun tidak benar:

``` nginx
server {
    listen 80;
    # listen 127.0.0.1:9090; # Varnish cache server
    server_name phpindonesia;
    root /home/sundi3yansyah/github/phpindonesia/phpindonesia.or.id-membership2;
    index index.html index.php;

    # Before, role by me
    # location / {
    #   try_files $uri $uri/ /index.php;
    # }

    # add from slime http://docs.slimframework.com/routing/rewrite/
    try_files $uri /index.php;

    location ~* \.(ico|css|js|gif|jpe?g|png)(\?[0-9]+)?$ {
        expires max;
        log_not_found off;
    }

    location ~* \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
        # Add from slime http://docs.slimframework.com/routing/rewrite/
        fastcgi_connect_timeout 3s;
        fastcgi_read_timeout 10s;
        # Or param script
        # fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
```

Output yang ditampilkan
_No input file specified._
Baik di URL `http://phpindonesia/` maupun di `http://phpindonesia/apps/membership`

**Comment by feryardiant** [comment]
cobain config ini bang

``` nginx
server {
    # your config
    root /path/to/docroot;
    index index.php index.html;

    location / {
        try_files  $uri $uri/ /index.php?$args;
    }

    location ~* ^.+\.(js|css|swf|xml|txt|ogg|ogv|svg|svgz|eot|otf|woff|ttf|mp4|rss|atom|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)$ {
        expires 24h;
        access_log off; # <- Gak perlu log sama sekali untuk static file.
        # log_not_found off;
    }

    location ~* \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
        # Add from slime http://docs.slimframework.com/routing/rewrite/
        # fastcgi_connect_timeout 3s;  # <- production only (for me at least)
        # fastcgi_read_timeout 10s;  # <- production only (for me at least)
        # Or param script
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }
}
```

**Comment by SunDi3yansyah** [comment]
Terimakasih kepada saudara @feryardiant yang telah meluangkan waktu untuk benang ini :smile:
Namun tetap tidak bisa, sudah saya coba beberapa config untuk selector dan propertinya. Tidak apa, ini akan menjadi PR saya. Untuk sementara akan saya assign kan ke apache. :clap:

**Comment by feryardiant** [comment]
hah? saya pake konfig itu dilokal bang :sweat_smile:

**Comment by feryardiant** [comment]
Entah napa, tp saya curiga apa jangan2 mungkin NginX atau PHP-FPM mu belum direstart?

Soalnya kebetulan jg lagi nyusun [_Skeleton App_](http://slimapp.projek.xyz) pake Slim dengan [NginX config](https://github.com/feryardiant/spa-skeleton/blob/develop/tests/heroku-app.conf) yang sama dan gak ada masalah bang.

**NB**: masih kosongan itu..

**Comment by feryardiant** [comment]
@SunDi3yansyah sorry content saya hapus, dipikir2 agak khawatir jg.

cc: @okaprinarjaya

**Comment by okaprinarjaya** [comment]
Halo mas @SunDi3yansyah , 

Terimakasih banyak untuk security bug reportnya. Senang sekali bug ini ditemukan.  Maka dari itulah pentingnya semua teman-teman pegiat ikut testing app ini. Tapi, sayangnya hanya sedikit yg tertarik.

**Comment by okaprinarjaya** [comment]
Mas @feryardiant , Terimakasih sudah menjaga data app ini. :+1:

**Comment by feryardiant** [comment]
vendor nya jangan lupa :sweat_smile:

**Comment by okaprinarjaya** [comment]
eh ini maen close ajaa.. 
blom saya test mas @feryardiant ,
nnti klo ternyata error seperti pull-request yg #39 gimana?

**Comment by feryardiant** [comment]
Kepencet :grin: 

> vendor

**Comment by okaprinarjaya** [comment]
Ok.. tested and run well

**Comment by okaprinarjaya** [comment]
Halo Mas @SunDi3yansyah , 

Nama perusahaan sudah dibackup blom ya? sebelum mencoba melakukan by pass kmarin? Saya harap mas @SunDi3yansyah  ada backupnya.

**Comment by SunDi3yansyah** [comment]
> Entah napa, tp saya curiga apa jangan2 mungkin NginX atau PHP-FPM mu belum direstart?
> 
> Soalnya kebetulan jg lagi nyusun Skeleton App pake Slim dengan NginX config yang sama dan gak ada masalah bang.
> 
> NB: masih kosongan itu..

Sudah saya restart mas, itu suatu kewajiban setelah merubah baris yang sudah diperbarui dalam config.

> @SunDi3yansyah sorry content saya hapus, dipikir2 agak khawatir jg.
> 
> cc: @okaprinarjaya

Iya tidak apa :+1: 

> Halo mas @SunDi3yansyah ,
> 
> Terimakasih banyak untuk security bug reportnya. Senang sekali bug ini ditemukan. Maka dari itulah pentingnya semua teman-teman pegiat ikut testing app ini. Tapi, sayangnya hanya sedikit yg tertarik.

Iya sama-sama :smile: 

> Halo Mas @SunDi3yansyah ,
> 
> Nama perusahaan sudah dibackup blom ya? sebelum mencoba melakukan by pass kmarin? Saya harap mas @SunDi3yansyah ada backupnya.

Mohon maaf tidak saya backup tapi nama company ID ke 1 - 3 tidak jauh dari nama deskripsinya, nama perusahaan ada didalam deskipsi tsb. hanya 3 ID yang saya rubah dan itu hanya di ID ke 1, 2, 3. Untuk mempermudah nge check-an portofolio sebaikkan tambahkan query search untuk portofolio untuk mengetahui siapa pemilik portofolio tsb.

Mohon maaf saya belum begitu familiar dengan slim sehingga belum bisa nge push apa yang seharusnya saya rubah untuk kontribusi diisni, tapi anggap saja ini bagian dari kontribusi saya.

**Comment by feryardiant** [comment]
gak perlu pake kata "anggap saja" ya ini memang yg namanya kontribusi.
:wink:

---

Best :)
Fery Wardiyanto

2015-11-08 19:32 GMT+07:00 Cahyadi Triyansyah notifications@github.com:
