### ISSUE TITLE
Update vendor dir

### ISSUE THREAD

**Issue by feryardiant** [phpindonesia/phpindonesia.or.id-membership2#41]
Salah satu known issue dari Slim yang dipake sekarang adalah path yang diakhiri dgn `/` itu tidak sama dengan path yang tidak diakhiri `/`. Contoh

[/apps/membership](http://www.phpindonesia.or.id/apps/membership) != [/apps/membership/](http://www.phpindonesia.or.id/apps/membership/)

Sempet liat issue nya di reponya slim, tp lupa karna udah agak lama.

cc: @okaprinarjaya

**Comment by okaprinarjaya** [comment]
apakah dengan update slim bisa solve issue /apps/membership != /apps/membership/ ?

**Comment by feryardiant** [comment]
belum sih :grin:
Karna ternyata itu bukan bug-nya slim tp fast-route.

tp, ayolah.. Kemaren nginstall SDK nya cloudinary dan slim & doctrine
ikutan keupdate. :sweat:

eniwe, pertimbangin jg sercurity nya bang. yg qu liat ada banyak sercurity
fixes di update yg baru.

---

Best :)
Fery Wardiyanto

**Comment by okaprinarjaya** [comment]
Ok..ada lib tambahan utk cloudinary ya,
Nanti malam saya mulai update

**Comment by okaprinarjaya** [comment]
Halo @feryardiant ,

Library cloudinary sudah saya tambahkan ke vendor melalui composer.json dan mengikuti dokumentasi di http://cloudinary.com/documentation/php_integration#getting_started_guide

Beberapa packages seperti doctrine juga ikut terupdate automatically.

Done.

**Comment by feryardiant** [comment]
Siap, thanks..

Saya mulai siang / sore ini..

---

Best :)
Fery Wardiyanto

2015-11-08 23:48 GMT+07:00 Oka Prinarjaya notifications@github.com:
