### ISSUE TITLE
tidak bisa simpan sosial media

### ISSUE THREAD

**Issue by andhikayuana** [phpindonesia/phpindonesia.or.id-membership2#50]
![12318003_1117184994981079_37629805_o](https://cloud.githubusercontent.com/assets/10376354/11607369/55ecd828-9b76-11e5-9e95-0bb8550d1ebf.jpg)

kronologi :
tambah akun sosial media, terus saya hapus (klik x), saya tambahkan lagi akun sosial medianya, terjadi error

**Comment by okaprinarjaya** [comment]
Halo mas @andhikayuana,
Terimakasih utk bug reportnya.
Mas @feryardiant, bisa bantu saya perbaiki ini?

**Comment by andhikayuana** [comment]
halo juga om @okaprinarjaya ,sama sama.
saya dari PHP Jogja, salam kenal. :smile:

**Comment by feryardiant** [comment]
Aduh. Maaf bang @okaprinarjaya, kebetulan lagi full nih. :sweat_smile:

**Comment by hyuzea** [comment]
nah ini yang saya coba perbaiki di #48  kemarin
tapi eh malah konflik doooh :smile:

**Comment by okaprinarjaya** [comment]
Gak masalah mas @feryardiant, :)

Oya, memang ada perubahan cukup banyak mas @supalpuket, jd tolong di pull ulang

**Comment by feryardiant** [comment]
See #62

**Comment by rulzi** [comment]
ini saya coba masih gak bisa untuk add baru dan hapus.
yang bisa hanya edit saja
@feryardiant @okaprinarjaya
