### ISSUE TITLE
Slim error di url /apps/membership/profile 

### ISSUE THREAD

**Issue by hyuzea** [phpindonesia/phpindonesia.or.id-membership2#53]
"Slim app error" di page /apps/membership/profile

saya ambil lagi yang terupdate ini d79fc03606ba8e7b4f4700daaf9abfc82b2b99cb
karena ketinggalan  commit  > 10 

.entah cuma saya atau bukan, tapi aplikasi error udah beberapa kali nge-pull / dowload zip masih enggak bisa. :D

**Comment by feryardiant** [comment]
Bisa diperjelas lagi pertanyaannya? Misal: errornya gimana? ada output apa? cloning atau installasi nya gimana?

**Comment by hyuzea** [comment]
.just "slim app error" kalo untuk page yang lain sih, saya nyobain yang ini /apps/membership/profile/edit atau /apps/membership/login itu bisa. saya juga belum ngecek bagian errornya.

**Comment by feryardiant** [comment]
Tambahkan baris

```
...
'mode' => 'development'
...
```

Di file `protected/settings.php` mu, biar detilnya bisa keliatan.

**Comment by hyuzea** [comment]
udah dari sananya sih, saya ambil yang terbaru ini, dan cuma rename file setting aja dan database

**Comment by okaprinarjaya** [comment]
Halo mas @supalpuket , 

Coba ganti value key 'mode' menjadi 'production'  di settings.php
`'mode' => 'production'`
Semenjak update ke Slim terbaru, default error 500 handler nya slim jadi aneh.. gak bisa muncul full trace lagi. Malah pakai custom error handler yg kami bikin sndiri malah bisa muncul detail errornya.. 

Oiya, app membership sudah menggunakan layanan cloudinary. Para kontributor bisa membuat akun cloudinary nya sendiri lalu menyesuaikan API key dan secret key di settings.php 

'cloudinary' => array(
            'cloud_name' => 'your_cloud_name',
            'api_key' => '12345',
            'api_secret' => 'xxxxx'
        )

Jika berkenan, bisa daftar melalui link referal ini http://cloudinary.com/invites/lpov9zyyucivvxsnalc5/qvzkjxrgrszqoahjzvmy?kind=facebook agar kami bisa dapat bonus bandwidth.

**Comment by okaprinarjaya** [comment]
http://cloudinary.com/invites/lpov9zyyucivvxsnalc5/qvzkjxrgrszqoahjzvmy?kind=facebook

**Comment by okaprinarjaya** [comment]
Hi @ALL , 

Untuk error handler sudah solved yaa disini https://github.com/phpindonesia/phpindonesia.or.id-membership2/commit/61b0516bd6de2ff193cfda5a57f83c23784d2233 

Jadi, mode development sudah kembali normal bisa menampilkan detail tracing error. Dan mode production hanya menampilkan error message saja.

**Comment by hyuzea** [comment]
eh maaf ini saya lupa [committed-tabel skill](https://github.com/phpindonesia/phpindonesia.or.id-membership2/commit/e03773b5de754e967a7f96b6b7454b9b1e53d6ab)nya 
udah bisa :grin:

**Comment by okaprinarjaya** [comment]
Itu bisa diketahui karena errornya sudah detail.
