### ISSUE TITLE
[Lapor] Field 'last_login' doesn't have a default value

### ISSUE THREAD

**Issue by feryardiant** [phpindonesia/phpindonesia.or.id-membership2#6]
![php indonesia - membership](https://cloud.githubusercontent.com/assets/508665/10817103/4d65c5a8-7e6a-11e5-9c82-3a37192d8947.png)

**Comment by okaprinarjaya** [comment]
Halo mas @feryardiant , 
Field last_login di db lokal memang tidak boleh NULL. Tapi db di production server boleh NULL. Hahaha maklum, belum ada migration. Jadi waktu itu saya menambahkan manual langsung by phpmyadmin di db production server table users. 

Sementara ini di production msh bekerja dng baik, coz belum ada laporan dari member bahwasannya juga dapat error yg sama seperti ini.
