### ISSUE TITLE
Something went wrong! pada edit profile

### ISSUE THREAD

**Issue by dwirachmatputra** [phpindonesia/phpindonesia.or.id-membership2#60]
http://www.phpindonesia.or.id/apps/membership/profile/edit

![screenshot from 2016-01-15 19 09 56](https://cloud.githubusercontent.com/assets/16718730/12352542/c1e4b3fc-bb7e-11e5-88b1-40a994b0c73d.png)

**Comment by feryardiant** [comment]
Hallo mas @dwirp

Ini saya close dulu y, karna related ama #59. Mungkin ntar malem baru bisa saya pegang karna pagi ini baru sampe rumah.

Thanks report nya, cheers :coffee:
