### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by YuriSuryarismawan** [phpindonesia/phpindonesia.or.id-membership2#61]
ga sengaja saya lagi edit profile terus muncul error seperti ini -> http://imgur.com/FEgxTIB

CMIIW xD

**Comment by feryardiant** [comment]
Hi ma @YuriSuryarismawan 

Yup, issue ini sedang saya tangani & berhubung ini duplicated dgn issue #59 jadi saya tutup dulu, biar gak redundant.

Thanks untuk report nya, :smile: :coffee:
