### ISSUE TITLE
Tanggal lahir

### ISSUE THREAD

**Issue by rakhaagung16** [phpindonesia/phpindonesia.or.id-membership2#7]
Selamat malam pak, mohon maaf mau tanya kenapa tanggal lahir harus kita input manual ya?
![image](https://cloud.githubusercontent.com/assets/15634103/10912519/796d0a1a-827c-11e5-8318-6e3723503d2f.png)

Sekalian tanya juga pak, ini kok saya bisa memasukan tahun yang melewati tahun di sistem?
![image](https://cloud.githubusercontent.com/assets/15634103/10912564/b7be3a46-827c-11e5-8656-197d489ca4fe.png)

Regrats : rakhaagung16

**Comment by feryardiant** [comment]
Butuh semacem datepicker gitu?

**Comment by rakhaagung16** [comment]
Yaps. Menurut saya butuh, dan juga kalau ga pake datepicker, saya bingung kok saya bisa input tahun diatas tahun pada sistem pak? Mohon maaf jika saya lancang hanya mengkritik. Terima kasih.

**Comment by feryardiant** [comment]
Kalo bisa ngirim pull request akan sangat membantu :smile:

**Comment by rakhaagung16** [comment]
hihihi sebagai technical support aja deh om :D Ilmu ane masih cetek ini juga sekalian belajar :) Tapi yang tanggal, jika memasukan 32 sudah tervalidasi tinggal tahun :D

**Comment by Andirohandi** [comment]
Kalau pake datepicker kayaknya kurang userfriendly malahan, soalnya kan tgl lahir tuh beda beda yah, smpe beda tahun juga. takutnya nanti malah lama nyari tanngal lahir nya kalau pake datepicker :v:

**Comment by okaprinarjaya** [comment]
Halo @rakhaagung16 , 

Terimakasih untuk laporan issue nya. Saya pikir jauh lebih nyaman input dengan ketik manual daripada menggunakan datepicker.
