### ISSUE TITLE
Warna tulisan dari tombol button

### ISSUE THREAD

**Issue by RonleyVinberk** [phpindonesia/phpindonesia.or.id-membership2#75]
![image](https://cloud.githubusercontent.com/assets/17139894/12913497/bc1438d0-cf51-11e5-8cd3-112c0ee3fd98.png)

**Comment by feryardiant** [comment]
Mau PR?

**Comment by RonleyVinberk** [comment]
Masih gagap kang kalau saya main cms. Masih saya pelajari dulu. :\

**Comment by feryardiant** [comment]
Oke sip. pantau terus.. :grin:

**Comment by mazipan** [comment]
fixed here : https://github.com/phpindonesia/phpindonesia.or.id-membership2/pull/91
tapi ada conflict.
minta tolong di resolved ya
