### ISSUE TITLE
Password Rule

### ISSUE THREAD

**Issue by wisn** [phpindonesia/phpindonesia.or.id-membership2#76]
Password is not allowed when we use special characters like "<" nor "%". Those special characters must be allowed for increasing our password security level. Many big companies recommend that our password should use special character like that.
Then, thank you if your deign with this issue.

**Comment by feryardiant** [comment]
Wanna send PR?

**Comment by wisn** [comment]
I'm forgot to add this into "feature request". Wait, I'll see the PHP Indonesia's system.

**Comment by feryardiant** [comment]
Please check latest update bro.. :smiley:

**Comment by wisn** [comment]
Cool! :+1:
Wanna contribute to this repository, but after national exam. :sob: 
More issues will be come later. See, ya!
