### ISSUE TITLE
Maaf, kenapa folder `vendor` tidak diikutkan?

### ISSUE THREAD

**Issue by hyuzea** [phpindonesia/phpindonesia.or.id-membership2#79]

**Comment by feryardiant** [comment]
Folder vendor adl folder dependencies yg bisa kita manage pake composer & kita gak bisa edit apapun yg ada didalamnya jadi gak perlu kita masukin. Cukup manage semua di `composer.json` dan `composer.lock` aja.

**Comment by feryardiant** [comment]
See #4

**Comment by aswitahidayat** [comment]
jadi mau bikin semua sendiri :)

**Comment by feryardiant** [comment]
waduh, bukannya gitu jg lah.. :sweat_smile:

Ide nya gini, paket dependensi itu seharusnya hanya digunakan di lokal kita selama development ataupun server ketika sudah production dan gak semestinya file2 tsb diikutsertakan di version control. Kenapa? Karna kita gak akan pernah dan "gak bisa" ngubah isinya, karna itu bukan urusane kita, toh kita masig bisa manage semuanya via dependensi manager yg kita pake. Dlm hal ini kita pake composer, ya pakelah `composer install` untuk nginstall apa yg kita butuhin selama development.

**Comment by hyuzea** [comment]
cheers!! I got it, thanks bang @feryardiant, 
saya mulai paham, kemarin install tanpa composer, ya jadinya error, librarynya gak ada, ngecek file composer.json, download manual library yang kurang.
berasa bertindak sbg composer :tired_face: maaf curhat  :grimacing: 

oh ya, sebaiknya tambahin composer sbg requirement di Readme.md-nya

**Comment by feryardiant** [comment]
Dibaca lagi readme.md nya pak :sweat_smile:
