### ISSUE TITLE
Butuh penambahan jenis pekerjaan pada saat pendaftaran menjadi member

### ISSUE THREAD

**Issue by titounnes** [phpindonesia/phpindonesia.or.id-membership2#8]
1. kolom pekerjaan ditambah. beberapa orang prpogramer bukan pekerjaan utama, seperti contyoh akademisi dan peneliti
2. ketika pendaftatran tidak lrngkasp sebagai contoh kota belum terisi, tapi propinsdi dsudah terisi, kota tidak bisa dpilih sebelum dipicu oleh onchange pada propinsi. sehingga pendaftar harus mengubah dulu ke propinsi lasin dan kembali ke propinsi sebelumnya. saran ditambahkan juga event onfocus pada kota lalu mengfambil data provinsi untuk menambahkan option pada kota.

**Comment by feryardiant** [comment]
Ada list lengkap kira-kira apa aja yg perlu ditambahkan?

**Comment by titounnes** [comment]
1. tasmpilan galery ketika di tablet 10" agak berantakan.

**Comment by titounnes** [comment]
beberapa orang menurut perngasmatanku 
pelerjaan:
guru, 
terkhnisi it di perguruasn tinggi
dosen.

**Comment by feryardiant** [comment]
Untuk saat ini saya close dulu. 

PR are prefered.
