### ISSUE TITLE
validasi nomor identitas (ktm)

### ISSUE THREAD

**Issue by kangarie** [phpindonesia/phpindonesia.or.id-membership2#86]
di kampus sy nomor KTM berawalan dengan huruf --> G54102011
namun validasi di sistem, tampaknya mengharuskan semua numeric

terima kasih
arie

**Comment by feryardiant** [comment]
Hi pak @kangarie.

Bisa tolong diperjelas lagi maksudnya gimana?

Thanks

**Comment by kangarie** [comment]
contoh KTM IPB
![image](https://windaalam.files.wordpress.com/2011/02/photo0427.jpg)

itu klo sy input akan error sbb
![image](https://cloud.githubusercontent.com/assets/4359219/14483445/4fef1768-0171-11e6-9889-a5d929825018.png)

**Comment by kangarie** [comment]
sepertinya ini regex nya ini harus digit ya?

![image](https://cloud.githubusercontent.com/assets/4359219/14483492/aeb5af28-0171-11e6-9a10-81f21d060ede.png)

**Comment by feryardiant** [comment]
Oh, Iya asumsi untuk no identitas memang sementara hanya angka. Jika berkenan saya tunggu PR nya :wink:

**Comment by aamsur** [comment]
saya boleh PR ?

**Comment by feryardiant** [comment]
Resolved #88
