### ISSUE TITLE
Activation Link not working

### ISSUE THREAD

**Issue by suciptoid** [phpindonesia/phpindonesia.or.id-membership2#87]
![screenshot from 2016-04-13 13-06-18](https://cloud.githubusercontent.com/assets/1310895/14484214/a4b462c4-0178-11e6-8cff-1c2ccb59b256.png)
Baru daftar kemarin, dan link untuk aktivasi menunjukan halaman not found.
http://membership.phpindonesia.or.id/activate/2956/b2c3775784c3a258ee38e7c97a4db419

**Comment by okaprinarjaya** [comment]
Fixed
