### ISSUE TITLE
License (Lisensi)

### ISSUE THREAD

**Issue by berviantoleo** [phpindonesia/phpindonesia.or.id-membership2#92]
Halo, saya tidak menemukan file lisensi dalam repositori ini. 
[https://github.com/phpindonesia/phpindonesia.or.id-membership2](https://github.com/phpindonesia/phpindonesia.or.id-membership2)

Saya menyarankan untuk terdapat lisensi dalam repository ini. Saya melihat repository ini menggunakan library yang menggunakan lisensi MIT. Seperti :

[https://github.com/phpindonesia/phpindonesia.or.id-membership2/blob/750630623b03fb33a3c8ea47461113de18b0d8c2/www/css/bootstrap.css](https://github.com/phpindonesia/phpindonesia.or.id-membership2/blob/750630623b03fb33a3c8ea47461113de18b0d8c2/www/css/bootstrap.css)

Sehingga dalam repository ini dapat menambahkan file lisensi MIT tersebut agar mempermudah melihat lisensi dari repositori ini. Dengan lisensi ini dapat mencegah penyalahgunaan repositori ini, seperti penggunaan repositori ini secara komersial tanpa pemberitahuan kepada pembuatnya.

**Comment by jayvdb** [comment]
@feryardiant , perhaps you could submit the lisence.md as a separate PR which can be merged quickly.
