### ISSUE TITLE
SMTP connect() failed after member registration

### ISSUE THREAD

**Issue by deryfebriantara** [phpindonesia/phpindonesia.or.id-membership2#94]
![selection_394](https://cloud.githubusercontent.com/assets/12095361/24850116/f677f4ca-1df8-11e7-8934-2f23be8e0cac.png)

**Comment by novrian** [comment]
+1

**Comment by agungsijawir** [comment]
Errornya "Connect Failed", besar kemungkinan server membership tidak dapat terhubung ke server smtp. cek setelan login ke mail server / ping dari server membership ke server mail?

**Comment by hyuzea** [comment]
siapa saja atau ada yang mau nge-fix & PR
itung-itung belajar berkontribusi ke komunitas

**Comment by herloct** [comment]
> Errornya "Connect Failed", besar kemungkinan server membership tidak dapat terhubung ke server smtp. cek setelan login ke mail server / ping dari server membership ke server mail?

Ini udah ada yg ngecek server SMTP-nya kah?

> siapa saja atau ada yang mau nge-fix & PR
> itung-itung belajar berkontribusi ke komunitas

Pinginnya sih oom, cuma ngeliat ga ada testing-nya jadi ngeri juga ngotak-atik kode-nya :cry:

**Comment by agungsijawir** [comment]
> Ini udah ada yg ngecek server SMTP-nya kah?

belum om @herloct .... 
apa gak japri ke om peter dulu?

**Comment by herloct** [comment]
> belum om @herloct ....
> apa gak japri ke om peter dulu?

Kayanya oom peter masih nunggu ada yang ngelamar jadi lead dev dulu oom, buat ngasih akses ke server/hosting...

**Comment by LIQRGV** [comment]
Om @herloct mau bantu buatin test-nya?
Saya lagi nyoba merbaikin SMTP-nya sih, pake third party ternyata.

**Comment by herloct** [comment]
> Saya lagi nyoba merbaikin SMTP-nya sih, pake third party ternyata.

Ane coba di lokal pake MailHog aman oom fungsi kirim email-nya. Mungkin problem-nya ada di server smtp-nya entah ga konek atau ada setting yg salah di production, atau gimana.  
CMIIW

**Comment by LIQRGV** [comment]
Ya emang cuma masalah konek ke SMTP server sih ini om harusnya...
Aku gak biasa juga pake third party soalnya.
Haha....

**Comment by chez14** [comment]
Masih bug nih sampai sekarang, blom ada yang cek ke Live Servernya? 😆 
![image](https://cloud.githubusercontent.com/assets/5555026/26822046/eabcb02e-4ad2-11e7-900f-fbc50830907c.png)

**Comment by chez14** [comment]
Btw untuk sementara coba pake Maildrill / Mailgun / Bikin akun Outlook/Google, trus setting sendiri smtpnya xD xD

**Comment by feryardiant** [comment]
Check PR #96

**Comment by chez14** [comment]
@feryardiant Wuish, naise, tinggal merge aja kalo gitu, lagi nunggu bagian testing gituan yah?

**Comment by deryfebriantara** [comment]
smpt sudah fixed, saya close aja ya agan2. terima kasih atas perhatiannya :)
